drop extension if exists "pg_net";


  create table "public"."activity_logs" (
    "id" uuid not null default gen_random_uuid(),
    "workspace_id" uuid not null,
    "task_id" bigint,
    "user_id" uuid not null,
    "action" text not null,
    "changes" jsonb,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."activity_logs" enable row level security;


  create table "public"."board_columns" (
    "id" uuid not null default gen_random_uuid(),
    "board_id" uuid not null,
    "name" text not null,
    "status_value" text not null,
    "color" text default '#8b5cf6'::text,
    "order_index" integer default 0,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."board_columns" enable row level security;


  create table "public"."boards" (
    "id" uuid not null default gen_random_uuid(),
    "workspace_id" uuid not null,
    "name" text not null,
    "order_index" integer default 0,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."boards" enable row level security;


  create table "public"."cron_logs" (
    "id" uuid not null default gen_random_uuid(),
    "job_name" text not null,
    "last_run" timestamp with time zone,
    "next_run" timestamp with time zone,
    "status" text default 'pending'::text,
    "error_message" text,
    "created_at" timestamp with time zone default now()
      );



  create table "public"."profiles" (
    "id" uuid not null default extensions.uuid_generate_v4(),
    "telegram_id" bigint not null,
    "username" text,
    "full_name" text,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
      );


alter table "public"."profiles" enable row level security;


  create table "public"."recurring_task_instances" (
    "id" uuid not null default gen_random_uuid(),
    "original_task_id" bigint not null,
    "instance_task_id" bigint not null,
    "instance_date" date not null,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."recurring_task_instances" enable row level security;


  create table "public"."subtasks" (
    "id" uuid not null default gen_random_uuid(),
    "task_id" bigint not null,
    "title" text not null,
    "description" text,
    "completed" boolean default false,
    "order_index" integer default 0,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
      );



  create table "public"."task_dependencies" (
    "task_id" bigint not null,
    "depends_on_task_id" bigint not null,
    "dependency_type" text default 'blocks'::text
      );


alter table "public"."task_dependencies" enable row level security;


  create table "public"."task_label_links" (
    "task_id" bigint not null,
    "label_id" uuid not null
      );



  create table "public"."task_labels" (
    "id" uuid not null default gen_random_uuid(),
    "name" text not null,
    "color" text default '#8b5cf6'::text,
    "workspace_id" uuid,
    "created_by" uuid,
    "created_at" timestamp with time zone default now()
      );



  create table "public"."task_templates" (
    "id" uuid not null default gen_random_uuid(),
    "workspace_id" uuid not null,
    "name" text not null,
    "description" text,
    "template_data" jsonb not null,
    "category" text default 'general'::text,
    "created_by" uuid not null,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
      );


alter table "public"."task_templates" enable row level security;


  create table "public"."task_time_logs" (
    "id" uuid not null default gen_random_uuid(),
    "task_id" bigint not null,
    "user_id" uuid not null,
    "time_spent" integer not null,
    "unit" text default 'minutes'::text,
    "notes" text,
    "logged_at" timestamp with time zone default now()
      );


alter table "public"."task_time_logs" enable row level security;


  create table "public"."tasks" (
    "id" bigint generated by default as identity not null,
    "title" text not null,
    "description" text,
    "status" text default 'todo'::text,
    "priority" text default 'medium'::text,
    "assignee_id" uuid,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now(),
    "due_date" date,
    "due_time" time without time zone,
    "position" integer default 0,
    "parent_task_id" bigint,
    "subtask_count" integer default 0,
    "subtask_completed" integer default 0,
    "workspace_id" uuid,
    "is_recurring" boolean default false,
    "recurrence_rule" text,
    "recurrence_next_date" date,
    "original_task_id" bigint
      );


alter table "public"."tasks" enable row level security;


  create table "public"."workspace_members" (
    "workspace_id" uuid not null,
    "user_id" uuid not null,
    "role" text not null default 'member'::text,
    "joined_at" timestamp with time zone default now()
      );


alter table "public"."workspace_members" enable row level security;


  create table "public"."workspaces" (
    "id" uuid not null default gen_random_uuid(),
    "name" text not null,
    "description" text,
    "owner_id" uuid not null,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
      );


alter table "public"."workspaces" enable row level security;

CREATE UNIQUE INDEX activity_logs_pkey ON public.activity_logs USING btree (id);

CREATE UNIQUE INDEX board_columns_pkey ON public.board_columns USING btree (id);

CREATE UNIQUE INDEX boards_pkey ON public.boards USING btree (id);

CREATE UNIQUE INDEX cron_logs_pkey ON public.cron_logs USING btree (id);

CREATE INDEX idx_activity_logs_task ON public.activity_logs USING btree (task_id);

CREATE INDEX idx_activity_logs_user ON public.activity_logs USING btree (user_id);

CREATE INDEX idx_activity_logs_workspace ON public.activity_logs USING btree (workspace_id);

CREATE INDEX idx_boards_workspace ON public.boards USING btree (workspace_id);

CREATE INDEX idx_recurring_instances_original ON public.recurring_task_instances USING btree (original_task_id);

CREATE INDEX idx_subtasks_task ON public.subtasks USING btree (task_id);

CREATE INDEX idx_task_dependencies_task ON public.task_dependencies USING btree (task_id);

CREATE INDEX idx_task_labels_label ON public.task_label_links USING btree (label_id);

CREATE INDEX idx_task_labels_task ON public.task_label_links USING btree (task_id);

CREATE INDEX idx_task_templates_category ON public.task_templates USING btree (category);

CREATE INDEX idx_task_templates_workspace ON public.task_templates USING btree (workspace_id);

CREATE INDEX idx_task_time_logs_task ON public.task_time_logs USING btree (task_id);

CREATE INDEX idx_tasks_assignee ON public.tasks USING btree (assignee_id);

CREATE INDEX idx_tasks_assignee_workspace ON public.tasks USING btree (assignee_id, workspace_id);

CREATE INDEX idx_tasks_description ON public.tasks USING gin (to_tsvector('english'::regconfig, description));

CREATE INDEX idx_tasks_due_date ON public.tasks USING btree (due_date);

CREATE INDEX idx_tasks_parent ON public.tasks USING btree (parent_task_id);

CREATE INDEX idx_tasks_recurrence_date ON public.tasks USING btree (recurrence_next_date);

CREATE INDEX idx_tasks_recurring ON public.tasks USING btree (is_recurring) WHERE (is_recurring = true);

CREATE INDEX idx_tasks_status ON public.tasks USING btree (status);

CREATE INDEX idx_tasks_status_workspace ON public.tasks USING btree (status, workspace_id);

CREATE INDEX idx_tasks_workspace ON public.tasks USING btree (workspace_id);

CREATE INDEX idx_workspace_members_role ON public.workspace_members USING btree (role);

CREATE INDEX idx_workspace_members_user ON public.workspace_members USING btree (user_id);

CREATE INDEX idx_workspaces_owner ON public.workspaces USING btree (owner_id);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX profiles_telegram_id_key ON public.profiles USING btree (telegram_id);

CREATE UNIQUE INDEX recurring_task_instances_pkey ON public.recurring_task_instances USING btree (id);

CREATE UNIQUE INDEX subtasks_pkey ON public.subtasks USING btree (id);

CREATE UNIQUE INDEX task_dependencies_pkey ON public.task_dependencies USING btree (task_id, depends_on_task_id);

CREATE UNIQUE INDEX task_label_links_pkey ON public.task_label_links USING btree (task_id, label_id);

CREATE UNIQUE INDEX task_labels_pkey ON public.task_labels USING btree (id);

CREATE UNIQUE INDEX task_templates_pkey ON public.task_templates USING btree (id);

CREATE UNIQUE INDEX task_time_logs_pkey ON public.task_time_logs USING btree (id);

CREATE UNIQUE INDEX tasks_pkey ON public.tasks USING btree (id);

CREATE UNIQUE INDEX workspace_members_pkey ON public.workspace_members USING btree (workspace_id, user_id);

CREATE UNIQUE INDEX workspaces_pkey ON public.workspaces USING btree (id);

alter table "public"."activity_logs" add constraint "activity_logs_pkey" PRIMARY KEY using index "activity_logs_pkey";

alter table "public"."board_columns" add constraint "board_columns_pkey" PRIMARY KEY using index "board_columns_pkey";

alter table "public"."boards" add constraint "boards_pkey" PRIMARY KEY using index "boards_pkey";

alter table "public"."cron_logs" add constraint "cron_logs_pkey" PRIMARY KEY using index "cron_logs_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."recurring_task_instances" add constraint "recurring_task_instances_pkey" PRIMARY KEY using index "recurring_task_instances_pkey";

alter table "public"."subtasks" add constraint "subtasks_pkey" PRIMARY KEY using index "subtasks_pkey";

alter table "public"."task_dependencies" add constraint "task_dependencies_pkey" PRIMARY KEY using index "task_dependencies_pkey";

alter table "public"."task_label_links" add constraint "task_label_links_pkey" PRIMARY KEY using index "task_label_links_pkey";

alter table "public"."task_labels" add constraint "task_labels_pkey" PRIMARY KEY using index "task_labels_pkey";

alter table "public"."task_templates" add constraint "task_templates_pkey" PRIMARY KEY using index "task_templates_pkey";

alter table "public"."task_time_logs" add constraint "task_time_logs_pkey" PRIMARY KEY using index "task_time_logs_pkey";

alter table "public"."tasks" add constraint "tasks_pkey" PRIMARY KEY using index "tasks_pkey";

alter table "public"."workspace_members" add constraint "workspace_members_pkey" PRIMARY KEY using index "workspace_members_pkey";

alter table "public"."workspaces" add constraint "workspaces_pkey" PRIMARY KEY using index "workspaces_pkey";

alter table "public"."activity_logs" add constraint "activity_logs_task_id_fkey" FOREIGN KEY (task_id) REFERENCES public.tasks(id) ON DELETE SET NULL not valid;

alter table "public"."activity_logs" validate constraint "activity_logs_task_id_fkey";

alter table "public"."activity_logs" add constraint "activity_logs_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."activity_logs" validate constraint "activity_logs_user_id_fkey";

alter table "public"."activity_logs" add constraint "activity_logs_workspace_id_fkey" FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE not valid;

alter table "public"."activity_logs" validate constraint "activity_logs_workspace_id_fkey";

alter table "public"."board_columns" add constraint "board_columns_board_id_fkey" FOREIGN KEY (board_id) REFERENCES public.boards(id) ON DELETE CASCADE not valid;

alter table "public"."board_columns" validate constraint "board_columns_board_id_fkey";

alter table "public"."boards" add constraint "boards_workspace_id_fkey" FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE not valid;

alter table "public"."boards" validate constraint "boards_workspace_id_fkey";

alter table "public"."profiles" add constraint "profiles_telegram_id_key" UNIQUE using index "profiles_telegram_id_key";

alter table "public"."recurring_task_instances" add constraint "recurring_task_instances_instance_task_id_fkey" FOREIGN KEY (instance_task_id) REFERENCES public.tasks(id) ON DELETE CASCADE not valid;

alter table "public"."recurring_task_instances" validate constraint "recurring_task_instances_instance_task_id_fkey";

alter table "public"."recurring_task_instances" add constraint "recurring_task_instances_original_task_id_fkey" FOREIGN KEY (original_task_id) REFERENCES public.tasks(id) ON DELETE CASCADE not valid;

alter table "public"."recurring_task_instances" validate constraint "recurring_task_instances_original_task_id_fkey";

alter table "public"."subtasks" add constraint "subtasks_task_id_fkey" FOREIGN KEY (task_id) REFERENCES public.tasks(id) ON DELETE CASCADE not valid;

alter table "public"."subtasks" validate constraint "subtasks_task_id_fkey";

alter table "public"."task_dependencies" add constraint "task_dependencies_dependency_type_check" CHECK ((dependency_type = ANY (ARRAY['blocks'::text, 'depends_on'::text, 'relates_to'::text]))) not valid;

alter table "public"."task_dependencies" validate constraint "task_dependencies_dependency_type_check";

alter table "public"."task_dependencies" add constraint "task_dependencies_depends_on_task_id_fkey" FOREIGN KEY (depends_on_task_id) REFERENCES public.tasks(id) ON DELETE CASCADE not valid;

alter table "public"."task_dependencies" validate constraint "task_dependencies_depends_on_task_id_fkey";

alter table "public"."task_dependencies" add constraint "task_dependencies_task_id_fkey" FOREIGN KEY (task_id) REFERENCES public.tasks(id) ON DELETE CASCADE not valid;

alter table "public"."task_dependencies" validate constraint "task_dependencies_task_id_fkey";

alter table "public"."task_label_links" add constraint "task_label_links_label_id_fkey" FOREIGN KEY (label_id) REFERENCES public.task_labels(id) ON DELETE CASCADE not valid;

alter table "public"."task_label_links" validate constraint "task_label_links_label_id_fkey";

alter table "public"."task_label_links" add constraint "task_label_links_task_id_fkey" FOREIGN KEY (task_id) REFERENCES public.tasks(id) ON DELETE CASCADE not valid;

alter table "public"."task_label_links" validate constraint "task_label_links_task_id_fkey";

alter table "public"."task_labels" add constraint "task_labels_created_by_fkey" FOREIGN KEY (created_by) REFERENCES public.profiles(id) ON DELETE SET NULL not valid;

alter table "public"."task_labels" validate constraint "task_labels_created_by_fkey";

alter table "public"."task_templates" add constraint "task_templates_created_by_fkey" FOREIGN KEY (created_by) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."task_templates" validate constraint "task_templates_created_by_fkey";

alter table "public"."task_templates" add constraint "task_templates_workspace_id_fkey" FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE not valid;

alter table "public"."task_templates" validate constraint "task_templates_workspace_id_fkey";

alter table "public"."task_time_logs" add constraint "task_time_logs_task_id_fkey" FOREIGN KEY (task_id) REFERENCES public.tasks(id) ON DELETE CASCADE not valid;

alter table "public"."task_time_logs" validate constraint "task_time_logs_task_id_fkey";

alter table "public"."task_time_logs" add constraint "task_time_logs_unit_check" CHECK ((unit = ANY (ARRAY['minutes'::text, 'hours'::text, 'days'::text]))) not valid;

alter table "public"."task_time_logs" validate constraint "task_time_logs_unit_check";

alter table "public"."task_time_logs" add constraint "task_time_logs_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."task_time_logs" validate constraint "task_time_logs_user_id_fkey";

alter table "public"."tasks" add constraint "tasks_assignee_id_fkey" FOREIGN KEY (assignee_id) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."tasks" validate constraint "tasks_assignee_id_fkey";

alter table "public"."tasks" add constraint "tasks_original_task_id_fkey" FOREIGN KEY (original_task_id) REFERENCES public.tasks(id) ON DELETE SET NULL not valid;

alter table "public"."tasks" validate constraint "tasks_original_task_id_fkey";

alter table "public"."tasks" add constraint "tasks_parent_task_id_fkey" FOREIGN KEY (parent_task_id) REFERENCES public.tasks(id) ON DELETE CASCADE not valid;

alter table "public"."tasks" validate constraint "tasks_parent_task_id_fkey";

alter table "public"."tasks" add constraint "tasks_priority_check" CHECK ((priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'urgent'::text]))) not valid;

alter table "public"."tasks" validate constraint "tasks_priority_check";

alter table "public"."tasks" add constraint "tasks_status_check" CHECK ((status = ANY (ARRAY['todo'::text, 'inprogress'::text, 'done'::text]))) not valid;

alter table "public"."tasks" validate constraint "tasks_status_check";

alter table "public"."tasks" add constraint "tasks_workspace_id_fkey" FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE not valid;

alter table "public"."tasks" validate constraint "tasks_workspace_id_fkey";

alter table "public"."workspace_members" add constraint "workspace_members_role_check" CHECK ((role = ANY (ARRAY['owner'::text, 'admin'::text, 'member'::text, 'viewer'::text]))) not valid;

alter table "public"."workspace_members" validate constraint "workspace_members_role_check";

alter table "public"."workspace_members" add constraint "workspace_members_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."workspace_members" validate constraint "workspace_members_user_id_fkey";

alter table "public"."workspace_members" add constraint "workspace_members_workspace_id_fkey" FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE not valid;

alter table "public"."workspace_members" validate constraint "workspace_members_workspace_id_fkey";

alter table "public"."workspaces" add constraint "workspaces_owner_id_fkey" FOREIGN KEY (owner_id) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."workspaces" validate constraint "workspaces_owner_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.generate_recurring_task_instance(task_id bigint)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
DECLARE
  v_task RECORD;
  v_next_date date;
BEGIN
  SELECT * INTO v_task FROM tasks WHERE id = task_id AND is_recurring = true;

  IF v_task IS NOT NULL THEN
    -- Calculate next date based on recurrence rule
    -- Simple implementation: daily, weekly, monthly
    IF v_task.recurrence_rule = 'daily' THEN
      v_next_date := CURRENT_DATE + INTERVAL '1 day';
    ELSIF v_task.recurrence_rule = 'weekly' THEN
      v_next_date := CURRENT_DATE + INTERVAL '7 days';
    ELSIF v_task.recurrence_rule = 'monthly' THEN
      v_next_date := CURRENT_DATE + INTERVAL '1 month';
    ELSE
      RETURN;
    END IF;

    -- Create new task instance
    INSERT INTO tasks (
      title, description, priority, status, assignee_id, workspace_id,
      due_date, due_time, is_recurring, recurrence_rule, original_task_id
    ) VALUES (
      v_task.title, v_task.description, v_task.priority, 'todo', v_task.assignee_id, v_task.workspace_id,
      v_next_date, v_task.due_time, true, v_task.recurrence_rule, v_task.id
    );

    -- Log the instance
    INSERT INTO recurring_task_instances (original_task_id, instance_task_id, instance_date)
    VALUES (v_task.id, currval('tasks_id_seq'), v_next_date);
  END IF;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.log_task_activity()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  INSERT INTO activity_logs (workspace_id, task_id, user_id, action, changes)
  VALUES (
    COALESCE(NEW.workspace_id, OLD.workspace_id),
    NEW.id,
    auth.uid(),
    CASE WHEN TG_OP = 'INSERT' THEN 'created' WHEN TG_OP = 'UPDATE' THEN 'updated' WHEN TG_OP = 'DELETE' THEN 'deleted' END,
    row_to_json(NEW)
  );
  RETURN NEW;
END;
$function$
;

grant delete on table "public"."activity_logs" to "anon";

grant insert on table "public"."activity_logs" to "anon";

grant references on table "public"."activity_logs" to "anon";

grant select on table "public"."activity_logs" to "anon";

grant trigger on table "public"."activity_logs" to "anon";

grant truncate on table "public"."activity_logs" to "anon";

grant update on table "public"."activity_logs" to "anon";

grant delete on table "public"."activity_logs" to "authenticated";

grant insert on table "public"."activity_logs" to "authenticated";

grant references on table "public"."activity_logs" to "authenticated";

grant select on table "public"."activity_logs" to "authenticated";

grant trigger on table "public"."activity_logs" to "authenticated";

grant truncate on table "public"."activity_logs" to "authenticated";

grant update on table "public"."activity_logs" to "authenticated";

grant delete on table "public"."activity_logs" to "service_role";

grant insert on table "public"."activity_logs" to "service_role";

grant references on table "public"."activity_logs" to "service_role";

grant select on table "public"."activity_logs" to "service_role";

grant trigger on table "public"."activity_logs" to "service_role";

grant truncate on table "public"."activity_logs" to "service_role";

grant update on table "public"."activity_logs" to "service_role";

grant delete on table "public"."board_columns" to "anon";

grant insert on table "public"."board_columns" to "anon";

grant references on table "public"."board_columns" to "anon";

grant select on table "public"."board_columns" to "anon";

grant trigger on table "public"."board_columns" to "anon";

grant truncate on table "public"."board_columns" to "anon";

grant update on table "public"."board_columns" to "anon";

grant delete on table "public"."board_columns" to "authenticated";

grant insert on table "public"."board_columns" to "authenticated";

grant references on table "public"."board_columns" to "authenticated";

grant select on table "public"."board_columns" to "authenticated";

grant trigger on table "public"."board_columns" to "authenticated";

grant truncate on table "public"."board_columns" to "authenticated";

grant update on table "public"."board_columns" to "authenticated";

grant delete on table "public"."board_columns" to "service_role";

grant insert on table "public"."board_columns" to "service_role";

grant references on table "public"."board_columns" to "service_role";

grant select on table "public"."board_columns" to "service_role";

grant trigger on table "public"."board_columns" to "service_role";

grant truncate on table "public"."board_columns" to "service_role";

grant update on table "public"."board_columns" to "service_role";

grant delete on table "public"."boards" to "anon";

grant insert on table "public"."boards" to "anon";

grant references on table "public"."boards" to "anon";

grant select on table "public"."boards" to "anon";

grant trigger on table "public"."boards" to "anon";

grant truncate on table "public"."boards" to "anon";

grant update on table "public"."boards" to "anon";

grant delete on table "public"."boards" to "authenticated";

grant insert on table "public"."boards" to "authenticated";

grant references on table "public"."boards" to "authenticated";

grant select on table "public"."boards" to "authenticated";

grant trigger on table "public"."boards" to "authenticated";

grant truncate on table "public"."boards" to "authenticated";

grant update on table "public"."boards" to "authenticated";

grant delete on table "public"."boards" to "service_role";

grant insert on table "public"."boards" to "service_role";

grant references on table "public"."boards" to "service_role";

grant select on table "public"."boards" to "service_role";

grant trigger on table "public"."boards" to "service_role";

grant truncate on table "public"."boards" to "service_role";

grant update on table "public"."boards" to "service_role";

grant delete on table "public"."cron_logs" to "anon";

grant insert on table "public"."cron_logs" to "anon";

grant references on table "public"."cron_logs" to "anon";

grant select on table "public"."cron_logs" to "anon";

grant trigger on table "public"."cron_logs" to "anon";

grant truncate on table "public"."cron_logs" to "anon";

grant update on table "public"."cron_logs" to "anon";

grant delete on table "public"."cron_logs" to "authenticated";

grant insert on table "public"."cron_logs" to "authenticated";

grant references on table "public"."cron_logs" to "authenticated";

grant select on table "public"."cron_logs" to "authenticated";

grant trigger on table "public"."cron_logs" to "authenticated";

grant truncate on table "public"."cron_logs" to "authenticated";

grant update on table "public"."cron_logs" to "authenticated";

grant delete on table "public"."cron_logs" to "service_role";

grant insert on table "public"."cron_logs" to "service_role";

grant references on table "public"."cron_logs" to "service_role";

grant select on table "public"."cron_logs" to "service_role";

grant trigger on table "public"."cron_logs" to "service_role";

grant truncate on table "public"."cron_logs" to "service_role";

grant update on table "public"."cron_logs" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

grant delete on table "public"."recurring_task_instances" to "anon";

grant insert on table "public"."recurring_task_instances" to "anon";

grant references on table "public"."recurring_task_instances" to "anon";

grant select on table "public"."recurring_task_instances" to "anon";

grant trigger on table "public"."recurring_task_instances" to "anon";

grant truncate on table "public"."recurring_task_instances" to "anon";

grant update on table "public"."recurring_task_instances" to "anon";

grant delete on table "public"."recurring_task_instances" to "authenticated";

grant insert on table "public"."recurring_task_instances" to "authenticated";

grant references on table "public"."recurring_task_instances" to "authenticated";

grant select on table "public"."recurring_task_instances" to "authenticated";

grant trigger on table "public"."recurring_task_instances" to "authenticated";

grant truncate on table "public"."recurring_task_instances" to "authenticated";

grant update on table "public"."recurring_task_instances" to "authenticated";

grant delete on table "public"."recurring_task_instances" to "service_role";

grant insert on table "public"."recurring_task_instances" to "service_role";

grant references on table "public"."recurring_task_instances" to "service_role";

grant select on table "public"."recurring_task_instances" to "service_role";

grant trigger on table "public"."recurring_task_instances" to "service_role";

grant truncate on table "public"."recurring_task_instances" to "service_role";

grant update on table "public"."recurring_task_instances" to "service_role";

grant delete on table "public"."subtasks" to "anon";

grant insert on table "public"."subtasks" to "anon";

grant references on table "public"."subtasks" to "anon";

grant select on table "public"."subtasks" to "anon";

grant trigger on table "public"."subtasks" to "anon";

grant truncate on table "public"."subtasks" to "anon";

grant update on table "public"."subtasks" to "anon";

grant delete on table "public"."subtasks" to "authenticated";

grant insert on table "public"."subtasks" to "authenticated";

grant references on table "public"."subtasks" to "authenticated";

grant select on table "public"."subtasks" to "authenticated";

grant trigger on table "public"."subtasks" to "authenticated";

grant truncate on table "public"."subtasks" to "authenticated";

grant update on table "public"."subtasks" to "authenticated";

grant delete on table "public"."subtasks" to "service_role";

grant insert on table "public"."subtasks" to "service_role";

grant references on table "public"."subtasks" to "service_role";

grant select on table "public"."subtasks" to "service_role";

grant trigger on table "public"."subtasks" to "service_role";

grant truncate on table "public"."subtasks" to "service_role";

grant update on table "public"."subtasks" to "service_role";

grant delete on table "public"."task_dependencies" to "anon";

grant insert on table "public"."task_dependencies" to "anon";

grant references on table "public"."task_dependencies" to "anon";

grant select on table "public"."task_dependencies" to "anon";

grant trigger on table "public"."task_dependencies" to "anon";

grant truncate on table "public"."task_dependencies" to "anon";

grant update on table "public"."task_dependencies" to "anon";

grant delete on table "public"."task_dependencies" to "authenticated";

grant insert on table "public"."task_dependencies" to "authenticated";

grant references on table "public"."task_dependencies" to "authenticated";

grant select on table "public"."task_dependencies" to "authenticated";

grant trigger on table "public"."task_dependencies" to "authenticated";

grant truncate on table "public"."task_dependencies" to "authenticated";

grant update on table "public"."task_dependencies" to "authenticated";

grant delete on table "public"."task_dependencies" to "service_role";

grant insert on table "public"."task_dependencies" to "service_role";

grant references on table "public"."task_dependencies" to "service_role";

grant select on table "public"."task_dependencies" to "service_role";

grant trigger on table "public"."task_dependencies" to "service_role";

grant truncate on table "public"."task_dependencies" to "service_role";

grant update on table "public"."task_dependencies" to "service_role";

grant delete on table "public"."task_label_links" to "anon";

grant insert on table "public"."task_label_links" to "anon";

grant references on table "public"."task_label_links" to "anon";

grant select on table "public"."task_label_links" to "anon";

grant trigger on table "public"."task_label_links" to "anon";

grant truncate on table "public"."task_label_links" to "anon";

grant update on table "public"."task_label_links" to "anon";

grant delete on table "public"."task_label_links" to "authenticated";

grant insert on table "public"."task_label_links" to "authenticated";

grant references on table "public"."task_label_links" to "authenticated";

grant select on table "public"."task_label_links" to "authenticated";

grant trigger on table "public"."task_label_links" to "authenticated";

grant truncate on table "public"."task_label_links" to "authenticated";

grant update on table "public"."task_label_links" to "authenticated";

grant delete on table "public"."task_label_links" to "service_role";

grant insert on table "public"."task_label_links" to "service_role";

grant references on table "public"."task_label_links" to "service_role";

grant select on table "public"."task_label_links" to "service_role";

grant trigger on table "public"."task_label_links" to "service_role";

grant truncate on table "public"."task_label_links" to "service_role";

grant update on table "public"."task_label_links" to "service_role";

grant delete on table "public"."task_labels" to "anon";

grant insert on table "public"."task_labels" to "anon";

grant references on table "public"."task_labels" to "anon";

grant select on table "public"."task_labels" to "anon";

grant trigger on table "public"."task_labels" to "anon";

grant truncate on table "public"."task_labels" to "anon";

grant update on table "public"."task_labels" to "anon";

grant delete on table "public"."task_labels" to "authenticated";

grant insert on table "public"."task_labels" to "authenticated";

grant references on table "public"."task_labels" to "authenticated";

grant select on table "public"."task_labels" to "authenticated";

grant trigger on table "public"."task_labels" to "authenticated";

grant truncate on table "public"."task_labels" to "authenticated";

grant update on table "public"."task_labels" to "authenticated";

grant delete on table "public"."task_labels" to "service_role";

grant insert on table "public"."task_labels" to "service_role";

grant references on table "public"."task_labels" to "service_role";

grant select on table "public"."task_labels" to "service_role";

grant trigger on table "public"."task_labels" to "service_role";

grant truncate on table "public"."task_labels" to "service_role";

grant update on table "public"."task_labels" to "service_role";

grant delete on table "public"."task_templates" to "anon";

grant insert on table "public"."task_templates" to "anon";

grant references on table "public"."task_templates" to "anon";

grant select on table "public"."task_templates" to "anon";

grant trigger on table "public"."task_templates" to "anon";

grant truncate on table "public"."task_templates" to "anon";

grant update on table "public"."task_templates" to "anon";

grant delete on table "public"."task_templates" to "authenticated";

grant insert on table "public"."task_templates" to "authenticated";

grant references on table "public"."task_templates" to "authenticated";

grant select on table "public"."task_templates" to "authenticated";

grant trigger on table "public"."task_templates" to "authenticated";

grant truncate on table "public"."task_templates" to "authenticated";

grant update on table "public"."task_templates" to "authenticated";

grant delete on table "public"."task_templates" to "service_role";

grant insert on table "public"."task_templates" to "service_role";

grant references on table "public"."task_templates" to "service_role";

grant select on table "public"."task_templates" to "service_role";

grant trigger on table "public"."task_templates" to "service_role";

grant truncate on table "public"."task_templates" to "service_role";

grant update on table "public"."task_templates" to "service_role";

grant delete on table "public"."task_time_logs" to "anon";

grant insert on table "public"."task_time_logs" to "anon";

grant references on table "public"."task_time_logs" to "anon";

grant select on table "public"."task_time_logs" to "anon";

grant trigger on table "public"."task_time_logs" to "anon";

grant truncate on table "public"."task_time_logs" to "anon";

grant update on table "public"."task_time_logs" to "anon";

grant delete on table "public"."task_time_logs" to "authenticated";

grant insert on table "public"."task_time_logs" to "authenticated";

grant references on table "public"."task_time_logs" to "authenticated";

grant select on table "public"."task_time_logs" to "authenticated";

grant trigger on table "public"."task_time_logs" to "authenticated";

grant truncate on table "public"."task_time_logs" to "authenticated";

grant update on table "public"."task_time_logs" to "authenticated";

grant delete on table "public"."task_time_logs" to "service_role";

grant insert on table "public"."task_time_logs" to "service_role";

grant references on table "public"."task_time_logs" to "service_role";

grant select on table "public"."task_time_logs" to "service_role";

grant trigger on table "public"."task_time_logs" to "service_role";

grant truncate on table "public"."task_time_logs" to "service_role";

grant update on table "public"."task_time_logs" to "service_role";

grant delete on table "public"."tasks" to "anon";

grant insert on table "public"."tasks" to "anon";

grant references on table "public"."tasks" to "anon";

grant select on table "public"."tasks" to "anon";

grant trigger on table "public"."tasks" to "anon";

grant truncate on table "public"."tasks" to "anon";

grant update on table "public"."tasks" to "anon";

grant delete on table "public"."tasks" to "authenticated";

grant insert on table "public"."tasks" to "authenticated";

grant references on table "public"."tasks" to "authenticated";

grant select on table "public"."tasks" to "authenticated";

grant trigger on table "public"."tasks" to "authenticated";

grant truncate on table "public"."tasks" to "authenticated";

grant update on table "public"."tasks" to "authenticated";

grant delete on table "public"."tasks" to "service_role";

grant insert on table "public"."tasks" to "service_role";

grant references on table "public"."tasks" to "service_role";

grant select on table "public"."tasks" to "service_role";

grant trigger on table "public"."tasks" to "service_role";

grant truncate on table "public"."tasks" to "service_role";

grant update on table "public"."tasks" to "service_role";

grant delete on table "public"."workspace_members" to "anon";

grant insert on table "public"."workspace_members" to "anon";

grant references on table "public"."workspace_members" to "anon";

grant select on table "public"."workspace_members" to "anon";

grant trigger on table "public"."workspace_members" to "anon";

grant truncate on table "public"."workspace_members" to "anon";

grant update on table "public"."workspace_members" to "anon";

grant delete on table "public"."workspace_members" to "authenticated";

grant insert on table "public"."workspace_members" to "authenticated";

grant references on table "public"."workspace_members" to "authenticated";

grant select on table "public"."workspace_members" to "authenticated";

grant trigger on table "public"."workspace_members" to "authenticated";

grant truncate on table "public"."workspace_members" to "authenticated";

grant update on table "public"."workspace_members" to "authenticated";

grant delete on table "public"."workspace_members" to "service_role";

grant insert on table "public"."workspace_members" to "service_role";

grant references on table "public"."workspace_members" to "service_role";

grant select on table "public"."workspace_members" to "service_role";

grant trigger on table "public"."workspace_members" to "service_role";

grant truncate on table "public"."workspace_members" to "service_role";

grant update on table "public"."workspace_members" to "service_role";

grant delete on table "public"."workspaces" to "anon";

grant insert on table "public"."workspaces" to "anon";

grant references on table "public"."workspaces" to "anon";

grant select on table "public"."workspaces" to "anon";

grant trigger on table "public"."workspaces" to "anon";

grant truncate on table "public"."workspaces" to "anon";

grant update on table "public"."workspaces" to "anon";

grant delete on table "public"."workspaces" to "authenticated";

grant insert on table "public"."workspaces" to "authenticated";

grant references on table "public"."workspaces" to "authenticated";

grant select on table "public"."workspaces" to "authenticated";

grant trigger on table "public"."workspaces" to "authenticated";

grant truncate on table "public"."workspaces" to "authenticated";

grant update on table "public"."workspaces" to "authenticated";

grant delete on table "public"."workspaces" to "service_role";

grant insert on table "public"."workspaces" to "service_role";

grant references on table "public"."workspaces" to "service_role";

grant select on table "public"."workspaces" to "service_role";

grant trigger on table "public"."workspaces" to "service_role";

grant truncate on table "public"."workspaces" to "service_role";

grant update on table "public"."workspaces" to "service_role";


  create policy "users can view workspace activity"
  on "public"."activity_logs"
  as permissive
  for select
  to public
using ((workspace_id IN ( SELECT workspace_members.workspace_id
   FROM public.workspace_members
  WHERE (workspace_members.user_id = auth.uid()))));



  create policy "Public profiles are viewable by everyone."
  on "public"."profiles"
  as permissive
  for select
  to public
using (true);



  create policy "profiles_public_read"
  on "public"."profiles"
  as permissive
  for select
  to public
using (true);



  create policy "profiles_user_update"
  on "public"."profiles"
  as permissive
  for update
  to public
using ((id = auth.uid()))
with check ((id = auth.uid()));



  create policy "members can create templates"
  on "public"."task_templates"
  as permissive
  for insert
  to public
with check ((workspace_id IN ( SELECT workspace_members.workspace_id
   FROM public.workspace_members
  WHERE (workspace_members.user_id = auth.uid()))));



  create policy "users can view workspace templates"
  on "public"."task_templates"
  as permissive
  for select
  to public
using ((workspace_id IN ( SELECT workspace_members.workspace_id
   FROM public.workspace_members
  WHERE (workspace_members.user_id = auth.uid()))));



  create policy "Public tasks are viewable by everyone."
  on "public"."tasks"
  as permissive
  for select
  to public
using (true);



  create policy "Users can insert own tasks"
  on "public"."tasks"
  as permissive
  for insert
  to public
with check (((auth.uid())::text = (assignee_id)::text));



  create policy "Users can update own tasks"
  on "public"."tasks"
  as permissive
  for update
  to public
using (((auth.uid())::text = (assignee_id)::text));



  create policy "tasks_authenticated_create"
  on "public"."tasks"
  as permissive
  for insert
  to public
with check (((auth.role() = 'authenticated'::text) OR (auth.role() = 'service_role'::text)));



  create policy "tasks_public_read"
  on "public"."tasks"
  as permissive
  for select
  to public
using (true);



  create policy "tasks_user_delete"
  on "public"."tasks"
  as permissive
  for delete
  to public
using (((assignee_id = auth.uid()) OR (auth.role() = 'service_role'::text)));



  create policy "tasks_user_update"
  on "public"."tasks"
  as permissive
  for update
  to public
using (((assignee_id = auth.uid()) OR (auth.role() = 'service_role'::text)))
with check (((assignee_id = auth.uid()) OR (auth.role() = 'service_role'::text)));



  create policy "admins/owners can manage members"
  on "public"."workspace_members"
  as permissive
  for all
  to public
using ((workspace_id IN ( SELECT workspace_members_1.workspace_id
   FROM public.workspace_members workspace_members_1
  WHERE ((workspace_members_1.user_id = auth.uid()) AND (workspace_members_1.role = ANY (ARRAY['admin'::text, 'owner'::text]))))));



  create policy "users can view workspace members"
  on "public"."workspace_members"
  as permissive
  for select
  to public
using ((workspace_id IN ( SELECT workspace_members_1.workspace_id
   FROM public.workspace_members workspace_members_1
  WHERE (workspace_members_1.user_id = auth.uid()))));



  create policy "only owners can delete workspace"
  on "public"."workspaces"
  as permissive
  for delete
  to public
using ((owner_id = auth.uid()));



  create policy "only owners can update workspace"
  on "public"."workspaces"
  as permissive
  for update
  to public
using ((owner_id = auth.uid()));



  create policy "users can view workspaces they're members of"
  on "public"."workspaces"
  as permissive
  for select
  to public
using (((auth.uid() IN ( SELECT workspace_members.user_id
   FROM public.workspace_members
  WHERE (workspace_members.workspace_id = workspaces.id))) OR (owner_id = auth.uid())));


CREATE TRIGGER task_activity_log AFTER INSERT OR UPDATE ON public.tasks FOR EACH ROW EXECUTE FUNCTION public.log_task_activity();


